### ISSUE TITLE
在windows环境下使用!!msr sync同步可能卡住

### ISSUE THREAD

**Issue by gi-b716** [EMUnion/MirrorServerReforged#7]
使用系统win11，python3.9.13，msr版本1.0.7。
在1.19.2服务器内使用!!msr sync同步，有时会显示一个同步中就卡住，使用!!msr start也会显示正在同步中 无法启动。查看后台发现报了个Traceback。
目前唯一办法：重启。
无法在log里找到traceback内容，待复现后截图上传。

**Comment by GamerNoTitle** [comment]
最好直接复制traceback内容 复现了再说吧

**Comment by bloodnighttw** [comment]
這邊遇到相同問題
```
Traceback (most recent call last):
  File "C:\Users\bntw\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\bntw\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bntw\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.pyt
    raise e from None
  File "C:\Users\bntw\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.pyt
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\MirrorServerReforged-v1.0.7.mcdr\mirror_server_reforged\__init__.py", line 131, in ServerSync
  File "C:\Users\bntw\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 560, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bntw\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 514, in _copytree
    raise Error(errors)
shutil.Error: [('./server/world\\level6001225915719516131.dat', './Mirror/server/world\\level6001225915719516131.dat', ]
```
Python版本3.11
MSR 1.07

**Comment by bloodnighttw** [comment]
這邊找到了解決辦法
修改MirrorServerReforged.json檔案中關於 路徑的符號
`/` -> '\\'
Example:
```json
{
  "world":[
    "world"
  ],
  "command":"python -m mcdreforged",
  "rcon":{
    "enable":true,
    "host":"localhost",
    "port":25579,
    "password":"1qaz2wsx"
  },
  "source":".\\server",
  "target":".\\Mirror\\server"
}
```

**Comment by HY916-cn** [comment]
https://github.com/EMUnion/MirrorServerReforged/issues/16
考虑查看此issue
目前更改已经合并至主仓库，请尝试更新到最新版本
