### ISSUE TITLE
更新python后插件失效

### ISSUE THREAD

**Issue by Allenobbin** [EMUnion/MirrorServerReforged#8]
如题，MCDR版本为最新，python版本为3.12.0。

**Comment by GamerNoTitle** [comment]
有没有报错的信息日志什么的贴一下？

**Comment by Allenobbin** [comment]
[MCDR] [2023-10-25 21:49:28] [MainThread/INFO]: MCDReforged正于Python 3.12.0环境中运行
[MCDR] [2023-10-25 21:49:28] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [2023-10-25 21:49:28] [TaskExecutor/INFO]: 插件 mirror_server_reforged@1.0.7 已加载
[MCDR] [2023-10-25 21:49:28] [TaskExecutor/ERROR]: Fail to load the entry point of mirror_server_reforged@1.0.7
Traceback (most recent call last):
  File "D:\Python\Lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 68, in _on_ready
    self._load_entry_instance()
  File "D:\Python\Lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 36, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "plugins\MirrorServerReforged-v1.0.7.mcdr\mirror_server_reforged\__init__.py", line 12, in <module>
    from setuptools import Command
ModuleNotFoundError: No module named 'setuptools'
[MCDR] [2023-10-25 21:49:28] [TaskExecutor/INFO]: 共加载: §71§r 个插件; 已加载插件数: §73§r
[MCDR] [2023-10-25 21:49:28] [MainThread/INFO]: 正在启动服务端，启动参数为 "java -jar -Xms1536M -Xmx1536M -server -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M fabric-server-launch.jar --nogui --port 11219 --universe D:\1.20.1Quilt\saves --world survival"
[MCDR] [2023-10-25 21:49:28] [MainThread/INFO]: 服务端正在以 PID 15304 运行中
[MCDR] [2023-10-25 21:50:39] [MainThread/INFO]: 服务端进程返回代码: 0
[MCDR] [2023-10-25 21:50:39] [MainThread/INFO]: 服务端已关闭
[MCDR] [2023-10-25 21:50:39] [MainThread/INFO]: 正在关闭 MCDR
[MCDR] [2023-10-25 21:50:39] [MainThread/INFO]: 正在关闭高级控制台
[MCDR] [2023-10-25 21:50:39] [MainThread/INFO]: bye

**Comment by GamerNoTitle** [comment]
看起来好像是缺少轮子，虽然我不知道为什么py3.12会没有这个,运行一下 `pip install setuptools`

**Comment by Allenobbin** [comment]
成功了，现在能用了。

**Comment by Twor** [comment]
> 看起来好像是缺少轮子，虽然我不知道为什么py3.12会没有这个,运行一下 `pip install setuptools`

同样的问题，建议写入依赖

**Comment by GamerNoTitle** [comment]
这个问题出现是因为Python3.12不再预装setuptools而导致的
晚点我改一下，去掉这玩意的依赖得了（手动吃瓜
